#!/usr/bin/env python3

from sys import exit

from helper import test

import gi
gi.require_version('ALSACtl', '0.0')
from gi.repository import ALSACtl

target = ALSACtl.Client()
props = (
    'name',
)
methods = (
    'open',
    'listen',
    'unlisten',
    'get_elem_list',
    'get_elem',
    'add_int_elems',
    'add_bool_elems',
    'add_enum_elems',
    'add_byte_elems',
    'add_iec60958_elems',
    'remove_elem',
)
signals = (
    'added',
)

if not test(target, props, methods, signals):
    exit(1)
