#!/usr/bin/env python3

from sys import exit
import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

client_number_enumerators = (
    'SYSTEM',
    'DUMMY',
    'OSS',
)

client_type_enumerators = (
    'NO_CLIENT',
    'USER_CLIENT',
    'KERNEL_CLIENT',
)

client_filter_flags = (
    'BROADCAST',
    'MULTICAST',
    'BOUNCE',
    'USE_EVENT',
)

port_number_enumerators = (
    'SYSTEM',
    'DUMMY',
    'OSS',
)

port_type_flags = (
    'SPECIFIC',
    'MIDI_GENERIC',
    'MIDI_GM',
    'MIDI_GS',
    'MIDI_XG',
    'MIDI_MT32',
    'MIDI_GM2',
    'SYNTH',
    'DIRECT_SAMPLE',
    'SAMPLE',
    'HARDWARE',
    'SOFTWARE',
    'SYNTHESIZER',
    'PORT',
    'APPLICATION',
)

port_cap_flags = (
    'READ',
    'WRITE',
    'SYNC_READ',
    'SYNC_WRITE',
    'DUPLEX',
    'SUBS_READ',
    'SUBS_WRITE',
    'NO_EXPORT',
)

types = {
    ALSASeq.ClientNumberEnum:   client_number_enumerators,
    ALSASeq.ClientTypeEnum:     client_type_enumerators,
    ALSASeq.ClientFilterFlag:   client_filter_flags,
    ALSASeq.PortNumberEnum:     port_number_enumerators,
    ALSASeq.PortTypeFlag:       port_type_flags,
    ALSASeq.PortCapFlag:        port_cap_flags,
}

for obj, types in types.items():
    for t in types:
        if not hasattr(obj, t):
            print('Enumerator {0} is not produced.'.format(t))
            exit(1)
