#!/usr/bin/env python3

from sys import exit
import gi
gi.require_version('ALSACtl', '0.0')
from gi.repository import ALSACtl

elem_type_enumerators = (
    'NONE',
    'BOOLEAN',
    'INTEGER',
    'ENUMERATED',
    'BYTES',
    'IEC958',
    'INTEGER64',
)

elem_iface_enumerators = (
    'CARD',
    'HWDEP',
    'MIXER',
    'PCM',
    'RAWMIDI',
    'TIMER',
    'SEQUENCER',
)

elem_access_flags = (
    'READ',
    'WRITE',
    'VOLATILE',
    'TIMESTAMP',
    'TLV_READ',
    'TLV_WRITE',
    'TLV_COMMAND',
    'INACTIVE',
    'LOCK',
    'OWNER',
    'TLV_CALLBACK',
    'USER',
)

event_mask_flags = (
    'VALUE',
    'INFO',
    'ADD',
    'TLV',
    'REMOVE',
)

types = {
    ALSACtl.ElemTypeEnum:   elem_type_enumerators,
    ALSACtl.ElemIfaceEnum:  elem_iface_enumerators,
    ALSACtl.ElemAccessFlag: elem_access_flags,
    ALSACtl.EventMaskFlag:  event_mask_flags,
}

for obj, types in types.items():
    for t in types:
        if not hasattr(obj, t):
            print('Enumerator {0} is not produced.'.format(t))
            exit(1)
