#!/usr/bin/env python3

from sys import exit

from helper import test

import gi
gi.require_version('ALSATimer', '0.0')
from gi.repository import ALSATimer

target = ALSATimer.Client()

props = (
    'id',
    'name',
    'flags',
    'card',
    'resolution',
    'params',
    'ticks',
    'queue-size',
    'filter',
)

methods = (
    'open',
    'get_timer_list',
    'select_timer',
    'get_status',
    'start',
    'stop',
    'resume',
)
signals = (
    'event',
)

if not test(target, props, methods, signals):
    exit(1)
