#!/usr/bin/env python3

from sys import exit
import gi
gi.require_version('ALSACtl', '0.0')
from gi.repository import ALSACtl

elem_type_enumerators = (
    'NONE',
    'BOOLEAN',
    'INTEGER',
    'ENUMERATED',
    'BYTES',
    'IEC958',
    'INTEGER64',
)

elem_iface_enumerators = (
    'CARD',
    'HWDEP',
    'MIXER',
    'PCM',
    'RAWMIDI',
    'TIMER',
    'SEQUENCER',
)

types = {
    ALSACtl.ElemTypeEnum:   elem_type_enumerators,
    ALSACtl.ElemIfaceEnum:  elem_iface_enumerators,
}

for obj, types in types.items():
    for t in types:
        if not hasattr(obj, t):
            print('Enumerator {0} is not produced.'.format(t))
            exit(1)
