#!/usr/bin/env python3

from sys import exit

from helper import test

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target = ALSASeq.Client()

props = (
    'number',
    'type',
    'name',
    'ports',
    'lost',
    'event-filter',
    'output-pool',
    'input-pool',
    'output-room',
    'output-free',
    'input-free',
)

methods = (
    'open',
    'update',
    'listen',
    'unlisten',
    'open_port',
    'close_port',
    'get_ports',
)
signals = ()

if not test(target, props, methods, signals):
    exit(1)
