#!/usr/bin/env python3

from sys import exit
import gi
gi.require_version('ALSATimer', '0.0')
from gi.repository import ALSATimer

device_class_enumerators = (
    'NONE',
    'SLAVE',
    'GLOBAL',
    'CARD',
    'PCM',
)

device_slave_class_enumerators = (
    'NONE',
    'APPLICATION',
    'SEQUENCER',
    'OSS_SEQUENCER',
)

global_device_type_enumerators = (
    'SYSTEM',
    'HPET',
    'HRTIMER',
)

device_info_flags = (
    'SLAVE',
)

device_param_flags = (
    'AUTO',
    'EXCLUSIVE',
    'EARLY_EVENT',
)

event_type_flag = (
    'RESOLUTION',
    'TICK',
    'START',
    'STOP',
    'CONTINUE',
    'PAUSE',
    'EARLY',
    'SUSPEND',
    'RESUME',
    'MSTART',
    'MSTOP',
    'MCONTINUE',
    'MPAUSE',
    'MSUSPEND',
    'MRESUME',
)

types = {
    ALSATimer.DeviceClassEnum:      device_class_enumerators,
    ALSATimer.DeviceSlaveClassEnum: device_slave_class_enumerators,
    ALSATimer.GlobalDeviceTypeEnum: global_device_type_enumerators,
    ALSATimer.DeviceInfoFlag:       device_info_flags,
    ALSATimer.DeviceParamFlag:      device_param_flags,
    ALSATimer.EventTypeFlag:        event_type_flag,
}

for obj, types in types.items():
    for t in types:
        if not hasattr(obj, t):
            print('Enumerator {0} is not produced.'.format(t))
            exit(1)
