#!/usr/bin/env python3

from sys import exit
import gi
gi.require_version('ALSARawmidi', '0.0')
from gi.repository import ALSARawmidi

stream_enumerators = (
    'OUTPUT',
    'INPUT',
)

types = {
    ALSARawmidi.StreamEnum: stream_enumerators,
}

for obj, types in types.items():
    for t in types:
        if not hasattr(obj, t):
            print('Enumerator {0} is not produced.'.format(t))
            exit(1)
