#!/usr/bin/env python3

from sys import exit
import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

client_number_enumerators = (
    'SYSTEM',
    'DUMMY',
    'OSS',
)

client_type_enumerators = (
    'NO_CLIENT',
    'USER_CLIENT',
    'KERNEL_CLIENT',
)

client_filter_flags = (
    'BROADCAST',
    'MULTICAST',
    'BOUNCE',
    'USE_EVENT',
)

port_number_enumerators = (
    'SYSTEM',
    'DUMMY',
    'OSS',
)

types = {
    ALSASeq.ClientNumberEnum:   client_number_enumerators,
    ALSASeq.ClientTypeEnum:     client_type_enumerators,
    ALSASeq.ClientFilterFlag:   client_filter_flags,
    ALSASeq.PortNumberEnum:     port_number_enumerators,
}

for obj, types in types.items():
    for t in types:
        if not hasattr(obj, t):
            print('Enumerator {0} is not produced.'.format(t))
            exit(1)
