#!/usr/bin/env python3

from sys import exit

from helper import test

import gi
gi.require_version('ALSASeq', '0.0')
from gi.repository import ALSASeq

target = ALSASeq.Port()

props = (
    'fd',
    'client-number',
    'number',
    'name',
    'type',
    'capabilities',
    'midi-channels',
    'midi-voices',
    'synth-voices',
    'cond-flags',
    'timestamp-queue',
    'read-use',
    'write-use',
)

methods = (
    'update',
)
signals = (
    'event',
)

if not test(target, props, methods, signals):
    exit(1)
