#ifndef __ALSA_GOBJECT_ALSACTL_ENUM_TYPES__H__
#define __ALSA_GOBJECT_ALSACTL_ENUM_TYPES__H__

#include <sound/asound.h>

typedef enum {
    ALSACTL_ELEM_TYPE_ENUM_NONE         = SNDRV_CTL_ELEM_TYPE_NONE,
    ALSACTL_ELEM_TYPE_ENUM_BOOLEAN      = SNDRV_CTL_ELEM_TYPE_BOOLEAN,
    ALSACTL_ELEM_TYPE_ENUM_INTEGER      = SNDRV_CTL_ELEM_TYPE_INTEGER,
    ALSACTL_ELEM_TYPE_ENUM_ENUMERATED   = SNDRV_CTL_ELEM_TYPE_ENUMERATED,
    ALSACTL_ELEM_TYPE_ENUM_BYTES        = SNDRV_CTL_ELEM_TYPE_BYTES,
    ALSACTL_ELEM_TYPE_ENUM_IEC958       = SNDRV_CTL_ELEM_TYPE_IEC958,
    ALSACTL_ELEM_TYPE_ENUM_INTEGER64    = SNDRV_CTL_ELEM_TYPE_INTEGER64,
} ALSACtlElemTypeEnum;

#endif
