#ifndef __ALSA_GOBJECT_ALSARAWMIDI_ENUM_TYPES__H__
#define __ALSA_GOBJECT_ALSARAWMIDI_ENUM_TYPES__H__

#include <sound/asound.h>

typedef enum {
    ALSARAWMIDI_STREAM_ENUM_OUTPUT  = SNDRV_RAWMIDI_STREAM_OUTPUT,
    ALSARAWMIDI_STREAM_ENUM_INPUT   = SNDRV_RAWMIDI_STREAM_INPUT,
} ALSARawmidiStreamEnum;

#endif
